AllCops:
  Include:
    - 'app/**/*'
  Exclude:
    - 'db/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'


Layout/EmptyLineAfterMagicComment:
  Enabled: true

Style/Documentation:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true