AllCops:
  NewCops: disable
  Include:
    - 'app/**/*'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'
    - 'app/views/**/*.html.erb'
    - 'app/views/**/*.text.erb'