apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: abdelkarimelbouroumi/task-ruby-api
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgres://postgres:recettebatch@postgres:5432/project_development"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32000
  selector:
    app: web
